import bigred2_separability_process
import numpy as np

experimental_parameters = {
    'q1_list': [0.01, 0.25, 0.5],
    'q2_list': [0.3],
    'q1': 'mu',
    'q2': 'input_fraction',
    'init_state': "zeros",
    'hamming_distance_range': np.linspace(0.0, 1., 20),
    'binomial_rate': 0.5,
    'sequence_length': 2000,
    'cut_length': 0,
    'num_trials_per_distance': 200,
    'input_fraction': 0.3,
    'input_gain': 1.0,
    'input_weight_bounds': (-0.2, 1.0),
    'neuron_type': 'sigmoid',
    'neuron_pars': {'c':1, 'e':10},
    'output_neuron_type': 'heaviside',
    'output_neuron_pars': {'threshold': 0.5},
    'num_reservoir_samplings': 85,
    'N': 500,
    'mu': 0.25,
    'k': 6,
    'maxk': 6,
    'minc':10,
    'maxc':10,
    'deg_exp':1.0,
    'lower_reservoir_bound': -0.2,
    'upper_reservoir_bound': 1.0,
    'reservoir_weight_scale': 1.132,
    'temp_dir_ID': 0, 
    'full_path': '/N/u/njrodrig/BigRed2/topology_of_function/',#'/nobackup/njrodrig/topology_of_function/',
    'worker_file': 'bigred2_separability_worker.py',
    'num_threads': 256,
    'command_prefix': 'perf_sep_N500_c1_e10_ws1.132_rsig0.3_mu',
    'qsub_nodes': 8,
    'qsub_ppn': 32,
    'qsub_time': '06:30:00',
    'qsub_cpu_type': 'cpu',
    'training_length': 1500,
    'validation_length': 1500,
    'binary':True,
    'cut': 500,
    'max_delay': 25,
    'shift': 1,
    'input_range': (0.0, 1.0)
}

bigred2_separability_process.run_qsub(experimental_parameters)